# Generated by Django 3.2.4 on 2021-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=2)),
                ('node_loc', models.CharField(max_length=10)),
                ('temp', models.IntegerField()),
                ('hum', models.IntegerField()),
                ('light', models.IntegerField()),
                ('snd', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
